# Generated by Django 3.0.14 on 2022-06-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20220626_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
